# Generated by Django 4.0.3 on 2022-03-11 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_role_status_volunteer_role_volunteer_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='volunteer',
            name='availability',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='volunteers.availability'),
        ),
    ]
